### PR TITLE
Added PS1 zealot level 2 "Unrest"

### PR DESCRIPTION
**Pull request by Moburma**
Added briefing text and .ini update to allow fully playing the unique second zealot level "Unrest" from the PS1 version of the game

### CODE REVIEW

**Comment by mefistotelis** [comment]
What's with the `mission109`? Just a mistake, or was it left empty on purpose?

**Comment by Moburma** [comment]
On purpose. I know it's not a limit now, but I kind of like keeping the "original" index numbers as they were. Even though there's nothing there in the zealot campaign, there was a 109 defined originally in ALL000.MIS. I did deliberate over this - I can definitely see it being a bit ugly and unnecessary, so I will change it if you prefer.

**Comment by mefistotelis** [comment]
I do not have any rules of keeping indexes empty if used in other campaigns; in fact, there are already many missions which break such rule.

On the other hand, I also don't care that much if there's an empty slot there or not.
(I recently did added a mission at end rather than replacing an empty slot, but it wasn't deliberate - I was focused on something else, so didn't thought of reusing a slot.)

If you want an empty slot, please expand the definition to what is done elsewhere, ie:
```
[mission109]
Name = MISSNO109
SourceID = 0
MapNo = 0
LevelNo = 0

[missuccess109]
; no objectives defined
```

..or you may remove the slot, if you prefer.

**Comment by Moburma** [comment]
Ahh sorry, I didn't realise the others were fully populated, my bad. I've removed the entry.

**Comment by mefistotelis** [comment]
The slot 109 seem to be missing completely now.
You probably see errors in log file about that.

Please either reorder the slots or fill the hole with what I proposed earlier.

**Comment by Moburma** [comment]
Ok, I added your definition for m109

**Pull request merged**
