### PR TITLE
swars: Make domes use new sound effect for opening and closing

### PR DESCRIPTION
**Pull request by Moburma**

### CODE REVIEW

**Comment by mefistotelis** [comment]
the sample_id=45 is already used by the game, conditionally during `collapse_building()`:
```
  if ( !ingame.SoundThing )
    play_dist_sample(p_building, 0x2Du, 0x7Fu, 0x40u, 100, 0, 3);
```

we should move to a different slot.

**Comment by mefistotelis** [comment]
Here is a list of play commands in the whole game - based on that you can check, with some accuracy, if the sample you've picked is used (some save sample numbers in variables..):

```
        play_sample_using_heap(0, 92, 127, 64, 100, 0, 3u);
                  play_sample_using_heap(0, 21, 127, 64, 100, -1, 1u);
                    play_sample_using_heap(0, 35, 127, 64, 100, 0, 1u);
            play_sample_using_heap(0, 21, 127, 64, 100, -1, 1u);
                          play_sample_using_heap(0, 21, 127, 64, 100, -1, 1u);
                        play_sample_using_heap(0, 21, 127, 64, 100, -1, 1u);
                    play_disk_sample(local_player_no, v11, 127, 64, 100, 0, 3);
                      play_disk_sample(0, v37, 127, 64, 100, 0, 3);
                      play_disk_sample(local_player_no, 0x2Cu, 127, 64, 100, 0, 3);
                play_sample_using_heap(0, 61, 127, 64, 5 * v6 + 90, 0, 3u);
                      play_disk_sample(local_player_no, weapon_sound_z[v42->U.UObject.unkn_4D], 127, 64, 100, 0, 3);
                      play_disk_sample(v12, weapon_sound[v42->U.UObject.unkn_4D], 127, 64, 100, 0, 3);
                  play_disk_sample(local_player_no, 0x2Cu, 127, 64, 100, 0, 3);
                play_sample_using_heap(0, 2, 127, 64, 100, 0, 3u);
      play_dist_sample(p_person, (p_person->U.UObject.MatrixIndex & 3) + 88, 0x7Fu, 0x40u, 100, 0, 1);
      play_dist_sample(p_person, (p_person->U.UObject.MatrixIndex & 3) + 88, 0x7Fu, 0x40u, 100, 0, 1);
        play_dist_sample(p_person, 0x25u, 0x7Fu, 0x40u, 100, 0, 3);
          play_dist_sample(p_person, 0x39u, 0x7Fu, 0x40u, 100, 0, 3);
          play_dist_sample(p_person, 0x19u, 0x7Fu, 0x40u, 100, 0, 3);
      play_dist_sample(p_person, 0x1Eu, 0x7Fu, 0x40u, 100, 0, 3);
        play_dist_sample(p_person1, 0x41u, 0x7Fu, 0x40u, 100, 0, 1);
          play_dist_sample(p_person1, 0x5Fu, 0x7Fu, 0x40u, 100, 0, 1);
            play_dist_sample(p_person1, sfx_woman_shot[((_BYTE)gameturn + (unsigned __int8)p_person1->ThingOffset) & 1], 0x7Fu,
            play_dist_sample(p_person1, sfx_man_shot[((_BYTE)gameturn + (unsigned __int8)p_person1->ThingOffset) & 7], 0x7Fu,
            play_dist_sample(p_person1, 0x41u, 0x7Fu, 0x40u, 100, 0, 1);
            play_dist_sample(p_person1, 0x25u, 0x7Fu, 0x40u, 100, 0, 3);
    play_dist_sample(p_person1, 0x39u, 0x7Fu, 0x40u, 100, 0, 3);
      play_dist_sample(p_person, sfx_woman_shot[((_BYTE)gameturn + (unsigned __int8)p_person->ThingOffset) & 1], 0x7Fu,
      play_dist_sample(p_person, sfx_man_shot[((_BYTE)gameturn + (unsigned __int8)p_person->ThingOffset) & 7], 0x7Fu,
    play_dist_sample(p_thing, 0x41u, 0x7Fu, 0x40u, 100, 0, 1);
      play_dist_sample(v7, 0x41u, 0x7Fu, 0x40u, 100, 0, 1);
          play_dist_ssample(p_sthing, 0x32u, 0x7Fu, 0x40u, 100, 0, 1);
    play_dist_sample(p_person, 0x4Fu, 0x7Fu, 0x40u, 100, -1, 3);
                  play_sample_using_heap(0, HIWORD(*(_DWORD *)&p_cmd->Next), 127, 64, 100, 0, 1u);
                  play_dist_sample(p_person, p_cmd->OtherThing, 0x7Fu, 0x40u, 100, 0, 1);
        play_dist_sample(p_person, 0x45u, 0x7Fu, 0x40u, 100, 0, 1);
        play_dist_sample(p_person, 0x40u, 0x7Fu, 0x40u, 100, 0, 1);
  play_dist_sample(v10, 0x37u, 0x7Fu, 0x40u, 100, 0, 1);
      play_sample_using_heap(0, 93, 127, 64, 100, -1, 3u);
    play_dist_sample(p_person, 2u, 0x7Fu, 0x40u, 100, 0, 1);
        play_dist_sample(p_person, (p_person->U.UPerson.ComCur & 3) + 88, 0x7Fu, 0x40u, 100, 0, 1);
          play_dist_sample(p_person, (p_person->U.UPerson.ComCur & 3) + 88, 0x7Fu, 0x40u, 100, 0, 1);
        play_dist_sample(p_person, 0xFu, 0x7Fu, 0x40u, 100, 0, 2);
              play_dist_sample(p_person, 14u, 0x7Fu, 0x40u, 100, -1, 2);
              play_dist_sample(p_person, 13u, 0x7Fu, 0x40u, 100, 0, 2);
            play_dist_sample(p_person, 52u, 0x7Fu, 0x40u, 100, -1, 3);
                play_dist_sample(p_person, 18u, 0x7Fu, 0x40u, 100, 0, 3);
                  play_dist_sample(p_person, 6u, 0x7Fu, 0x40u, 100, 0, 3);
              play_dist_sample(p_person, 5u, 0x7Fu, 0x40u, 100, 0, 3);
              play_dist_sample(p_person, 0x1Cu, 0x7Fu, 0x40u, 100, 0, 3);
      play_dist_ssample(p_sthing, 0x35u, 0x7Fu, 0x40u, 100, 0, 1);
    play_dist_ssample(p_sthing, 0x1Du, 0x7Fu, 0x40u, 100, 0, 2);
      play_dist_ssample(p_sthing, 0x2Fu, 0x7Fu, 0x40u, 100, 0, 3);
            play_dist_ssample(v28, 0x17u, 0x7Fu, 0x40u, 100, 0, 3);
            play_dist_ssample(v28, 0x2Fu, 0x7Fu, 0x40u, 100, 0, 3);
          play_dist_ssample(&sthings[v20], 0x1Du, 0x7Fu, 0x40u, 100, 0, 2);// inlined call process_static
    play_dist_sample(p_person, 0x81u, 0x7Fu, 0x40u, 100, 0, 3);
    play_dist_ssample(inited, 0x25u, 0x7Fu, 0x40u, 100, 0, 3);
      play_sample_using_heap(0, 96, 127, 64, 100, 0, 3u);
                          play_dist_sample(v13, 0x25u, 0x7Fu, 0x40u, 100, 0, 3);
                        play_dist_sample(v8, 0x5Fu, 0x7Fu, 0x40u, 100, 0, 1);
      play_dist_ssample((struct SimpleThing *)p_person, 0x25u, 0x7Fu, 0x40u, 100, 0, 3);
                    play_dist_sample(p_thingc, 0x5Fu, 0x7Fu, 0x40u, 100, 0, 1);
    play_dist_sample(p_building, 0x2Du, 0x7Fu, 0x40u, 100, 0, 3);
              play_dist_ssample(inited, 0x20u, 0x7Fu, 0x40u, 100, -1, 3);
              play_dist_ssample(v15, 0x1Fu, 0x7Fu, 0x40u, 100, -1, 3);
            play_dist_ssample(p_static, 0x25u, 0x7Fu, 0x40u, 100, 0, 3);
        play_dist_ssample(p_static, 0x36u, 0x7Fu, 0x40u, 100, 0, 1);
          play_dist_ssample(p_static, 0x25u, 0x3Cu, 0x40u, 100, 0, 3);
    play_dist_sample(p_thing, 0x14u, 0x7Fu, 0x40u, 100, 0, 3);
  play_dist_sample(p_person, 0x13u, 0x7Fu, 0x40u, 100, 0, 3);
    play_dist_sample(p_person, 20u, 127u, 64u, 100, 0, 3);
        play_dist_sample(v3, (v5 & 1) + v4, 0x7Fu, 0x40u, 100, 0, 1);
        play_sample_using_heap(0, 115, 127, 64, 100, 0, 3u);
      play_sample_using_heap(0, 135, 127, 64, 100, 0, 3u);
          play_sample_using_heap(0, 80, 127, 64, 100, 0, 1u);
          play_sample_using_heap(0, 80, 127, 64, 100, 0, 1u);
              play_sample_using_heap(0, 80, 127, 64, 100, 0, 1u);
    play_sample_using_heap(0, 78, 64, 64, 100, -1, 2u);
    play_sample_using_heap(0, 8, 64, 64, 100, -1, 2u);
    play_sample_using_heap(0, 77, 64, 64, 100, -1, 2u);
          play_dist_sample(p_veh, 0x11u, 0x7Fu, 0x40u, 100, 0, 1);
      play_dist_sample(s, 0x31u, 0x7Fu, 0x40u, 100, -1, 1);
    play_dist_sample(p_mech, 0x63u, 0x7Fu, 0x40u, 100, 0, 3);
      play_dist_sample(p_vehicle, 0x31u, 0x7Fu, 0x40u, 100, -1, 1);
        play_dist_sample(p_thing, 0x62u, 0x7Fu, 0x40u, 100, 0, 1);
        play_dist_sample(p_vehicle, 0x62u, 0x7Fu, 0x40u, 100, 0, 1);
    play_dist_sample(p_vehicle, 0x61u, 0x7Fu, 0x40u, 100, 0, 1);
    play_dist_sample(p_thing, v2 % 4 + 225, 0x7Fu, 0x40u, 100, 0, 1);
        play_dist_sample(p_turret, 47u, 127u, 0x40u, 100, 0, 1);
      play_dist_sample(p_turret, 48u, 127u, 0x40u, 100, -1, 1);
                  play_dist_sample(p_vehicle, v19 % 4 + 225, 0x7Fu, 0x40u, 100, 0, 1);
  play_dist_sample(p_thing, 0x25u, 0x7Fu, 0x40u, 100, 0, 3);
        play_dist_sample(p_vehicle, 9u, 0x7Fu, 0x40u, 100, -1, 1);
    play_dist_sample(p_thing, 0x25u, 0x7Fu, 0x40u, 100, 0, 3);
                    play_sample_using_heap(0, 111, 127, 64, 100, 0, 2u);
    play_sample_using_heap(0, 71, 127, 64, 100, 0, 3u);
            play_sample_using_heap(0, 111, 127, 64, 100, 0, 2u);
        play_sample_using_heap(0, 123, 127, 64, 100, 0, 1u);
        play_sample_using_heap(0, 110, 127, 64, 100, 0, 1u);
        play_sample_using_heap(0, 110, 127, 64, 100, 0, 1u);
          play_sample_using_heap(0, 124, 127, 64, 100, landmap_8BC, 1u);
          play_sample_using_heap(0, 128, 127, 64, 100, 0, 1u);
              play_sample_using_heap(0, 111, 127, 64, 100, 0, 2u);
        play_sample_using_heap(0, 129, 127, 64, 100, 0, 2u);
      play_sample_using_heap(0, 111, 127, 64, 100, 0, 2u);
        play_sample_using_heap(0, 123, 127, 64, 100, 0, 1u);
          play_sample_using_heap(0, 129, 127, 64, 100, 0, 2u);
          play_sample_using_heap(0, 111, 127, 64, 100, 0, 2u);
          play_sample_using_heap(0, 123, 127, 64, 100, 0, 1u);
              play_sample_using_heap(0, 129, 127, 64, 100, 0, 2u);
              play_sample_using_heap(0, 111, 127, 64, 100, 0, 2u);
            play_sample_using_heap(0, 123, 127, 64, 100, 0, 1u);
              play_sample_using_heap(0, 111, 127, 64, 100, 0, 2u);
              play_sample_using_heap(0, 111, 127, 64, 100, 0, 2u);
            play_sample_using_heap(0, 112, 127, 64, 100, 0, 1u);
        play_sample_using_heap(0, 123, 127, 64, 100, 0, 1u);
            v45 = play_sample_using_heap(0, 111, 127, 64, 100, 0, 2u);
              v45 = play_sample_using_heap(0, v50 % 3 + 119, 127, 64, 100, 0, 3u);
            play_sample_using_heap(0, 112, 127, 64, 100, 0, 1u);
        play_sample_using_heap(0, 123, 127, 64, 100, 0, 1u);
          play_sample_using_heap(0, 111, 127, 64, 100, 0, 2u);
      play_sample_using_heap(0, v15 % 3 + 119, 127, 64, 100, 0, 3u);
  play_sample_using_heap(0, 122, 127, 64, 100, -1, 3u);
      play_sample_using_heap(0, 122, 127, 64, 100, -1, 3u);
      play_sample_using_heap(0, 122, 127, 64, 100, -1, 3u);
      play_sample_using_heap(0, 113, 127, 64, 100, 0, 3u);
    play_sample_using_heap(0, 118, 127, 64, 100, 0, 3u);
  play_sample_using_heap(0, 114, 127, 64, 100, 0, 3u);
        play_sample_using_heap(0, 94, 127, 64, 100, 0, 3u);
      play_sample_using_heap(0, 110, 127, 64, 100, 0, 1u);
        play_sample_using_heap(0, 110, 127, 64, 100, 0, 1u);
            play_sample_using_heap(0, 125, 127, 64, 100, 0, 1u);
            play_sample_using_heap(0, 125, 127, 64, 100, 0, 1u);
            play_sample_using_heap(0, 125, 127, 64, 100, 0, 1u);
      play_sample_using_heap(0, 110, 127, 64, 100, 0, 1u);
        play_sample_using_heap(0, 123, 127, 64, 100, 0, 1u);
            play_sample_using_heap(0, 111, 127, 64, 100, 0, 2u);
            play_sample_using_heap(0, 129, 127, 64, 100, 0, 2u);
        play_sample_using_heap(0, 111, 127, 64, 100, 0, 2u);
    play_sample_using_heap(0, 129, 127, 64, 100, 0, 2u);
    play_sample_using_heap(0, 110, 127, 64, 100, 0, 1u);
        play_sample_using_heap(0, 110, 127, 64, 100, 0, 1u);
        play_dist_ssample(scale_effect, 0x44u, 0x7Fu, 0x40u, 100, 0, 1);
    play_dist_ssample(v31, 3u, 0x7Fu, 0x40u, 100, 0, 3);
        play_dist_ssample(scale_effect, 0x44u, 0x7Fu, 0x40u, 100, 0, 1);
    play_dist_ssample(v28, 3u, 0x7Fu, 0x40u, 100, 0, 3);
        play_dist_ssample(scale_effect, 0x44u, 0x7Fu, 0x40u, 100, 0, 1);
    play_dist_ssample(v30, 3u, 0x7Fu, 0x40u, 100, 0, 3);
  play_dist_sample(p_owner, 0x27u, 0x7Fu, 0x40u, 100, 0, 1);
    play_dist_ssample(v8, 0x28u, 0x7Fu, 0x40u, 100, 0, 1);
  play_dist_ssample(v14, 0x28u, 0x7Fu, 0x40u, 100, 0, 1);
            play_dist_sample(v5, 0x25u, 0x7Fu, 0x40u, 100, 0, 3);
    play_dist_sample(v3, 0x42u, 0x7Fu, 0x40u, 100, 0, 3);
        play_dist_ssample(inited, 1u, 0x7Fu, 0x40u, 100, 0, 3);
        play_dist_sample(p_person, (p_person->U.UPerson.ComCur & 3) + 88, 0x7Fu, 0x40u, 100, 0, 2);
            play_dist_sample(p_person, v25 + 80, 0x7Fu, 0x40u, v55, -1, 3);
            play_dist_sample(p_person, v28 + 84, 0x7Fu, 0x40u, 100, -1, 3);
          play_dist_sample(p_person, 0x24u, 0x7Fu, 0x40u, 100, 0, 2);
          play_dist_sample(p_person, 0x24u, 0x7Fu, 0x40u, 100, 0, 2);
          play_dist_sample(p_person, 0x24u, 0x7Fu, 0x40u, 100, 0, 2);
          play_dist_sample(p_person, 0x21u, 0x7Fu, 0x40u, 100, 0, 3);
            play_dist_sample(p_person, 7u, 0x7Fu, 0x40u, 100, -1, 3);
    play_dist_sample(p_person, 0x43u, 0x7Fu, 0x40u, 100, -1, 1);
      play_dist_sample(v10, 0x18u, 0x7Fu, 0x40u, 100, 0, 3);
    play_dist_sample(&things[(unsigned __int16)p_explode->field_38], 0x16u, 0x7Fu, 0x40u, 100, 0, 3);
    play_dist_sample(p_person, 0x1Du, 0x7Fu, 0x40u, 100, -1, 2);
      play_dist_sample(v3, 0x18u, 0x7Fu, 0x40u, 100, 0, 3);
        play_dist_sample(v3, 0x18u, 0x7Fu, 0x40u, 100, 0, 3);
        play_dist_ssample(p_mine, 0x26u, 0x7Fu, 0x40u, 100, -1, 1);
        play_dist_ssample(p_mine, 0x26u, 0x7Fu, 0x40u, 100, -1, 1);
          play_dist_ssample(inited, 1u, 0x7Fu, 0x40u, 100, 0, 3);
          play_dist_ssample(inited, 0x22u, 0x7Fu, 0x40u, 100, 0, 2);
          play_dist_ssample(inited, 1u, 0x7Fu, 0x40u, 100, 0, 3);
          play_dist_ssample(p_sthing, 0x22u, 0x7Fu, 0x40u, 100, 0, 2);
            play_dist_ssample(v10, 0x20u, 0, 0x40u, 100, -1, 3);
            play_dist_ssample(v10, 0x1Fu, 0, 0x40u, 100, -1, 3);
      play_dist_sample(v2, 0x33u, 0x7Fu, 0x40u, 100, 0, 3);
          play_dist_ssample(p_sthing, 0x38u, 4 * p_sthing->Timer1, 0x40u, 100, -1, 1);
      play_dist_ssample(p_sthing, 0x38u, 2 * (50 - p_sthing->Timer1), 0x40u, 100, -1, 1);
        play_dist_ssample(p_sthing, 0x2Cu, 2 * (50 - p_sthing->Timer1), 0x40u, 100, -1, 1);
          play_dist_ssample(p_sthing, 0x2Cu, 2 * (50 - p_sthing->Timer1), 0x40u, 100, -1, 1);
      play_sample_using_heap(0, dword_155704, 127, 64, 100, 0, 3u);
  play_sample_using_heap(0, 1, 127, 64, 100, -1, 3u);
      play_sample_using_heap(0, v10 % 5 + 7, 127, 64, 100, 0, 3u);
      play_sample_using_heap(0, 132, 127, 64, 100, 0, 3u);
            play_sample_using_heap(0, 126, 127, 64, 100, 0, 1u);
          play_sample_using_heap(0, 134, 127, 64, 100, 0, 3u);
      play_sample_using_heap(0, 127, 127, 64, 100, 0, 1u);
      play_sample_using_heap(0, 126, 127, 64, 100, 0, 1u);
      play_sample_using_heap(0, 117, 127, 64, 100, 0, 1u);
              play_sample_using_heap(0, 116, 127, 64, 100, 0, 1u);
  play_sample_using_heap(0, v7 % 3 + 119, 127, 64, 100, 0, 3u);
      play_sample_using_heap(0, v10 % 3 + 119, 127, 64, 100, 0, 3u);
    play_dist_ssample(v7, sample, 0x7Fu, 0x40u, 100, *(int *)((char *)&vol + 2) >> 16, 1);
    play_sample_using_heap((unsigned __int16)p_thing->ThingOffset, v23, v16, v12, pitch, loop, type);
    play_sample_using_heap(*(int *)&p_thing->Radius >> 16, v22, v16, v12, pitch, loop, type);
  play_sample_using_heap(9999, sample + 129, vol, pan, pitch, loop, type);
    play_dist_sample(p_thing, samp + 129, vol, pan,
        play_dist_ssample(v295, 0x10u, 0x7Fu, 0x40u, 100, -1, 1);
          play_sample_using_heap(0, 71, 127, 64, 100, 0, 3u);
                  play_sample_using_heap(0, 74, 127, 64, 100, 0, 3u);
                  play_sample_using_heap(0, 72, 127, 64, 100, 0, 3u);
                play_sample_using_heap(0, 75, 127, 64, 100, 0, 3u);
          play_sample_using_heap(0, 76, 127, 64, 100, 0, 3u);
        play_sample_using_heap(0, 73, 127, 64, 100, 0, 3u);
        play_sample_using_heap(0, 70, 127, 64, 100, 0, 3u);
```

**Comment by Moburma** [comment]
Thanks. Weird that 45 was in use, considering it's blank, I wonder what was there. I've chosen 100 for now, that seems clear.

**Comment by mefistotelis** [comment]
> I've chosen 100 for now, that seems clear.

I was unable to prove otherwise in reasonable time. Seem unused.

**Pull request merged**
